site_name: Clumper Docs
repo_url: https://github.com/donaldKelly17/clumper
site_url: https://donaldkelly17.github.io/clumper/
plugins:
    - mkdocstrings:
        watch:
          - clumper
    - search
theme:
    name: material
    palette:
        primary: purple
        accent: cyan
    font:
        text: Ubuntu
        code: Ubuntu Mono
    icon:
        logo: material/cloud
markdown_extensions:
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
